name: Generate release changelog

on:
  release:
    types: [published]

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Build and upload release changelog

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Echo github ref
        run: |
          echo "${{ github.ref }}"

      - name: Echo ref from env
        run: |
          echo "${{ env.GITHUB_REF }}"

      - name: Echo github event release tag name
        run: |
          echo "${{ github.event.release.tag_name }}"
